using System.ComponentModel.DataAnnotations;

namespace Kpmg.Web.Models;

/// <summary>A photograph attached to a complaint.</summary>
public class ComplaintPhoto
{
    public int Id { get; set; }

    public int ComplaintId { get; set; }

    public Complaint? Complaint { get; set; }

    /// <summary>Original file name supplied by the citizen (display only).</summary>
    [MaxLength(260)]
    public string OriginalFileName { get; set; } = string.Empty;

    /// <summary>Name of the file on disk, generated by the server.</summary>
    [MaxLength(100)]
    public string StoredFileName { get; set; } = string.Empty;

    [MaxLength(100)]
    public string ContentType { get; set; } = string.Empty;

    public long SizeInBytes { get; set; }
}
